import { defineDocs } from "@farming-labs/docs";
import { colorful } from "@farming-labs/theme/colorful";

export default defineDocs({
  entry: "docs",
  theme: colorful(),
  metadata: {
    titleTemplate: "%s – Docs",
    description: "Generated by @farming-labs/docs Cloud",
  },
});
